import 'package:json_annotation/json_annotation.dart';
import '../../../../core/utils/database_date_utils.dart';
import '../../../../shared/constants/database_constants.dart';

part 'email_verification.g.dart';

/// Email Verification domain model
///
/// Represents a verification code sent to a user's email during registration.
/// Codes expire after 15 minutes for security and are single-use.
///
/// Security features:
/// - 6-digit verification code
/// - 15-minute expiration window
/// - Single-use enforcement (is_used flag)
/// - Automatic cleanup after 24 hours
@JsonSerializable()
class EmailVerification {
  final String id;
  final String email;
  final String code;
  final DateTime createdAt;
  final DateTime expiresAt;
  final DateTime? verifiedAt;
  final bool isUsed;

  const EmailVerification({
    required this.id,
    required this.email,
    required this.code,
    required this.createdAt,
    required this.expiresAt,
    this.verifiedAt,
    this.isUsed = false,
  });

  // JSON serialization (auto-generated by build_runner)
  factory EmailVerification.fromJson(Map<String, dynamic> json) =>
      _$EmailVerificationFromJson(json);

  Map<String, dynamic> toJson() => _$EmailVerificationToJson(this);

  // Database conversion (manual - handles DateTime and boolean conversion)
  /// Creates EmailVerification from database row
  ///
  /// Handles SQLite-specific conversions:
  /// - INTEGER (0/1) → bool
  /// - TEXT (ISO 8601) → DateTime
  /// - Uses DatabaseConstants for column names
  factory EmailVerification.fromDatabase(Map<String, dynamic> map) {
    return EmailVerification(
      id: map[EMAIL_VERIFICATION_ID] as String,
      email: map[EMAIL_VERIFICATION_EMAIL] as String,
      code: map[EMAIL_VERIFICATION_CODE] as String,
      createdAt: DatabaseDateUtils.fromString(
          map[EMAIL_VERIFICATION_CREATED_AT] as String),
      expiresAt: DatabaseDateUtils.fromString(
          map[EMAIL_VERIFICATION_EXPIRES_AT] as String),
      verifiedAt: map[EMAIL_VERIFICATION_VERIFIED_AT] != null
          ? DatabaseDateUtils.fromString(
              map[EMAIL_VERIFICATION_VERIFIED_AT] as String)
          : null,
      isUsed: (map[EMAIL_VERIFICATION_IS_USED] as int) == 1,
    );
  }

  /// Converts EmailVerification to database row map
  ///
  /// Handles Dart → SQLite conversions:
  /// - bool → INTEGER (0/1)
  /// - DateTime → TEXT (ISO 8601)
  /// - Uses DatabaseConstants for column names
  Map<String, dynamic> toDatabase() {
    return {
      EMAIL_VERIFICATION_ID: id,
      EMAIL_VERIFICATION_EMAIL: email,
      EMAIL_VERIFICATION_CODE: code,
      EMAIL_VERIFICATION_CREATED_AT: DatabaseDateUtils.toTimestamp(createdAt),
      EMAIL_VERIFICATION_EXPIRES_AT: DatabaseDateUtils.toTimestamp(expiresAt),
      EMAIL_VERIFICATION_VERIFIED_AT:
          verifiedAt != null ? DatabaseDateUtils.toTimestamp(verifiedAt!) : null,
      EMAIL_VERIFICATION_IS_USED: isUsed ? 1 : 0,
    };
  }

  // Validation methods
  /// Checks if the verification code has expired
  ///
  /// Returns true if the current time is past the expiration time.
  bool isExpired() {
    return DateTime.now().isAfter(expiresAt);
  }

  /// Checks if the verification code is valid for use
  ///
  /// A code is valid if:
  /// - It has not been used
  /// - It has not expired
  bool isValid() {
    return !isUsed && !isExpired();
  }

  /// Calculates seconds remaining until expiration
  ///
  /// Returns 0 if already expired, otherwise returns remaining seconds.
  /// Useful for countdown timers in the UI.
  int get secondsUntilExpiration {
    if (isExpired()) {
      return 0;
    }
    return expiresAt.difference(DateTime.now()).inSeconds;
  }

  // Immutable update helper
  /// Creates a copy of this EmailVerification with specified fields replaced
  ///
  /// Useful for marking as used after successful verification.
  EmailVerification copyWith({
    String? id,
    String? email,
    String? code,
    DateTime? createdAt,
    DateTime? expiresAt,
    DateTime? verifiedAt,
    bool? isUsed,
  }) {
    return EmailVerification(
      id: id ?? this.id,
      email: email ?? this.email,
      code: code ?? this.code,
      createdAt: createdAt ?? this.createdAt,
      expiresAt: expiresAt ?? this.expiresAt,
      verifiedAt: verifiedAt ?? this.verifiedAt,
      isUsed: isUsed ?? this.isUsed,
    );
  }
}
