// ignore_for_file: constant_identifier_names

import '../../../shared/constants/database_constants.dart';

/// Migration V9: Sleep Phases
///
/// Adds `sleep_phases` table to define sleep stage types (deep, light, REM, wake).
/// Adds `sleep_record_sleep_phases` table to store detailed sleep stage segments for each sleep record.
/// Seeds the `sleep_phases` table with default values.
/// Adds indexes for performance.

const String MIGRATION_V9_CREATE_PHASES_TABLE = '''
CREATE TABLE IF NOT EXISTS $TABLE_SLEEP_PHASES (
  $SLEEP_PHASES_ID INT PRIMARY KEY,
  $SLEEP_PHASES_NAME TEXT NOT NULL
);
''';

const String MIGRATION_V9_CREATE_RECORD_PHASES_TABLE = '''
CREATE TABLE IF NOT EXISTS $TABLE_SLEEP_RECORD_SLEEP_PHASES (
  $SLEEP_RECORD_SLEEP_PHASES_ID TEXT PRIMARY KEY,
  $SLEEP_RECORD_SLEEP_PHASES_STARTED_AT TEXT NOT NULL,
  $SLEEP_RECORD_SLEEP_PHASES_DURATION INT NOT NULL,
  $SLEEP_RECORD_SLEEP_PHASES_SLEEP_PHASE_ID INT NOT NULL,
  $SLEEP_RECORD_SLEEP_PHASES_RECORD_ID TEXT NOT NULL,
  FOREIGN KEY ($SLEEP_RECORD_SLEEP_PHASES_SLEEP_PHASE_ID) REFERENCES $TABLE_SLEEP_PHASES($SLEEP_PHASES_ID) ON DELETE CASCADE,
  FOREIGN KEY ($SLEEP_RECORD_SLEEP_PHASES_RECORD_ID) REFERENCES $TABLE_SLEEP_RECORDS($SLEEP_RECORDS_ID) ON DELETE CASCADE
);
''';

const String MIGRATION_V9_INDEX_SLEEP_PHASES = '''
CREATE UNIQUE INDEX IF NOT EXISTS idx_name
  ON $TABLE_SLEEP_PHASES($SLEEP_PHASES_NAME)
''';

const String MIGRATION_V9_INDEX_SLEEP_RECORD_PHASES = '''
CREATE INDEX IF NOT EXISTS idx_started_at
  ON $TABLE_SLEEP_RECORD_SLEEP_PHASES($SLEEP_RECORD_SLEEP_PHASES_STARTED_AT)
''';

const String MIGRATION_V9_INSERT_SLEEP_PHASES = '''
INSERT INTO $TABLE_SLEEP_PHASES 
($SLEEP_PHASES_ID, $SLEEP_PHASES_NAME)
VALUES
  ($SLEEP_PHASE_DEEP, 'deep'),
  ($SLEEP_PHASE_LIGHT, 'light'),
  ($SLEEP_PHASE_REM, 'rem'),
  ($SLEEP_PHASE_WAKE, 'wake');
''';
